routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('/auth')->name('auth.')->group(function () {
    
    // Admin Routes
    Route::get('/admin_login',  'Auth\Admin\LoginController@loginPage')->name('admin_login');
    Route::post('/login_admin',  'Auth\Admin\LoginController@login')->name('login_admin');
    Route::get('/logout_admin',  'Auth\Admin\LoginController@logout')->name('logout_admin');
    // End of Admin Routes
});


Route::prefix('/admin')->name('admin.')->group(function () {
    #Dashboard Routes
    Route::get('/dashboard',  'Admin\DashboardController@dashboard')->name('dashboard');

    // Component Routes

    // Mandate Routes
    Route::get('/component/mandate/index',  'Admin\Component\MandateController@index')->name('component.mandate.index');
    Route::post('/component/mandate/store',  'Admin\Component\MandateController@storeMandate')->name('component.mandate.store');
    Route::post('/component/mandate/update',  'Admin\Component\MandateController@updateMandate')->name('component.mandate.update');
    Route::get('/component/mandate/status/{id}',  'Admin\Component\MandateController@mandateStatus')->name('component.mandate.status');
    // End of Mandate Routes

    // Mission Routes
    Route::get('/component/mission/index',  'Admin\Component\MissionController@index')->name('component.mission.index');
    Route::post('/component/mission/store',  'Admin\Component\MissionController@storeMission')->name('component.mission.store');
    Route::post('/component/mission/update',  'Admin\Component\MissionController@updateMission')->name('component.mission.update');
    Route::get('/component/mission/status/{id}',  'Admin\Component\MissionController@missionStatus')->name('component.mission.status');
    // End of Mission Routes

    // Vision Routes
    Route::get('/component/vision/index',  'Admin\Component\VisionController@index')->name('component.vision.index');
    Route::post('/component/vision/store',  'Admin\Component\VisionController@storeVision')->name('component.vision.store');
    Route::post('/component/vision/update',  'Admin\Component\VisionController@updateVision')->name('component.vision.update');
    Route::get('/component/vision/status/{id}',  'Admin\Component\VisionController@visionStatus')->name('component.vision.status');
    // End of Vision Routes

    // End of Component Routes

    // Blog Routes
    Route::get('/blog/index',  'Admin\BlogController@index')->name('blog.blog_index');
    Route::get('/blog/add',  'Admin\BlogController@addBlog')->name('blog.blog_add');
    Route::post('/blog/store',  'Admin\BlogController@storeBlog')->name('blog.blog_store');
    Route::get('/blog/edit/{id}',  'Admin\BlogController@editBlog')->name('blog.blog_edit');
    Route::post('/blog/update',  'Admin\BlogController@updateBlog')->name('blog.blog_update');
    Route::get('/blog/status/{id}',  'Admin\BlogController@blogStatus')->name('blog.blog_status');
    // End of Blog Routes

    // Admin Routes
    Route::get('/user/admin/index',  'Admin\User\AdminController@index')->name('user.admin.index');
    Route::get('/user/admin/add',  'Admin\User\AdminController@addAdmin')->name('user.admin.add');
    Route::post('/user/admin/store',  'Admin\User\AdminController@storeAdmin')->name('user.admin.store');
    Route::get('/user/admin/edit/{id}',  'Admin\User\AdminController@editAdmin')->name('user.admin.edit');
    Route::post('/user/admin/update',  'Admin\User\AdminController@updateAdmin')->name('user.admin.update');
    Route::get('/user/admin/status/{id}',  'Admin\User\AdminController@adminStatus')->name('user.admin.status');
    // End of Admin Routes

    // Admin Profile Routes
    Route::get('/user/admin/profile',  'Admin\User\AdminController@profile')->name('user.admin.profile');
    Route::post('/user/admin/profile_update',  'Admin\User\AdminController@updateProfile')->name('user.admin.profile_update');
    // End of Admin Profile Routes

     // Team Routes
     Route::get('/team/index',  'Admin\TeamController@index')->name('team.team_index');
     Route::post('/team/store',  'Admin\TeamController@storeTeam')->name('team.team_store');
     Route::get('/team/edit/{id}',  'Admin\TeamController@editTeam')->name('team.team_edit');
     Route::post('/team/update',  'Admin\TeamController@updateTeam')->name('team.team_update');
     Route::get('/team/status/{id}',  'Admin\TeamController@teamStatus')->name('team.team_status');
     Route::get('/team/delete/{id}',  'Admin\TeamController@deleteTeam')->name('team.team_delete');
     // End of Team Routes

     // Event Routes
     Route::get('/event/index',  'Admin\EventController@index')->name('event.event_index');
     Route::post('/event/store',  'Admin\EventController@storeEvent')->name('event.event_store');
     Route::get('/event/edit/{id}',  'Admin\EventController@editEvent')->name('event.event_edit');
     Route::post('/event/update',  'Admin\EventController@updateEvent')->name('event.event_update');
     Route::get('/event/status/{id}',  'Admin\EventController@eventStatus')->name('event.event_status');
    //  Route::get('/event/delete/{id}',  'Admin\EventController@deleteEvent')->name('event.event_delete');
     // End of Event Routes
});

    
    // Welcome Routes
    Route::get('/',  'Welcome\WelcomeController@index');
    // End of Welcome Routes

app/Http/Controllers/Admin/Component/MandateController.php
<?php

namespace App\Http\Controllers\Admin\Component;

use App\Http\Controllers\Controller;
use Auth;
use Session;
use App\Mandate;
use Illuminate\Http\Request;

class MandateController extends Controller
{
    public function __construct() {

        $this->middleware('auth:admin');
    }
    
    public function index() { 
        $mandates = Mandate::all();
        return view('admin.component.mandate', compact('mandates'));
    }
    
    public function storeMandate(Request $request){

        $this->validate($request, [
            "mandate"  => "required",
        ]);
  
        $mandate = new Mandate;
  
        $mandate->name = $request->mandate;
  
        if($mandate->save() == true){
          Session::flash('success', 'Mandate has been added successfully');
        }else{
          Session::flash('error', 'Could not add Mandate');
        }
        return redirect(route('admin.component.mandate.index'));
    }

    public function updateMandate(Request $request){

        $mandateId = $request->mandate_id;

        $mandate = Mandate::find($mandateId);

        $mandate->name = $request->mandate_name;

        if ($mandate->update() == true) {
            Session::flash('success', 'Mandate Updated Successfully');
        }else{
            Session::flash('failed', 'Error while Updating Mandate');
        }
        return redirect(route('admin.component.mandate.index'));
    }

    public function mandateStatus($id) {

        $mandateID = Mandate::find($id);

        if ($mandateID->status == true) {
            $mandateID->status = false;
            $mandateID->update();
                
            $mandates = Mandate::where('id', '!=', $id)->get();
            if($mandates){
                foreach($mandates as $mandate){
                    $mandate->status = true;
                    $mandate->update();
                }
            }
            Session::flash('success', strtoupper($mandateID->name).' disabled successfully!');
        }
        else{
            $mandateID->status = true;
            $mandateID->update();
                
            $mandates = Mandate::where('id', '!=', $id)->get();
            if($mandates){
                foreach($mandates as $mandate){
                    $mandate->status = false;
                    $mandate->update();
                }
            }
            Session::flash('success', strtoupper($mandateID->name).' activated successfully!');
        }
        return back();
    }

}

app/Http/Controllers/Admin/Component/MissionController.php
<?php

namespace App\Http\Controllers\Admin\Component;

use App\Http\Controllers\Controller;
use Auth;
use Session;
use App\Mission;
use Illuminate\Http\Request;

class MissionController extends Controller
{
    public function __construct() {

        $this->middleware('auth:admin');
    }
    
    public function index() { 
        $missions = Mission::all();
        return view('admin.component.mission', compact('missions'));
    }
    
    public function storeMission(Request $request){

        $this->validate($request, [
            "mission"  => "required",
        ]);
  
        $mission = new Mission;
  
        $mission->name = $request->mission;
  
        if($mission->save() == true){
          Session::flash('success', 'Mission has been added successfully');
        }else{
          Session::flash('error', 'Could not add Mission');
        }
        return redirect(route('admin.component.mission.index'));
    }

    public function updateMission(Request $request){

        $missionId = $request->mission_id;

        $mission = Mission::find($missionId);

        $mission->name = $request->mission_name;

        if ($mission->update() == true) {
            Session::flash('success', 'Mission Updated Successfully');
        }else{
            Session::flash('failed', 'Error while Updating Mission');
        }
        return redirect(route('admin.component.mission.index'));
    }

    public function missionStatus($id) {

        $missionID = Mission::find($id);

        if ($missionID->status == true) {
            $missionID->status = false;
            $missionID->update();
                
            $missions = Mission::where('id', '!=', $id)->get();
            if($missions){
                foreach($missions as $mission){
                    $mission->status = true;
                    $mission->update();
                }
            }
            Session::flash('success', strtoupper($missionID->name).' disabled successfully!');
        }
        else{
            $missionID->status = true;
            $missionID->update();
                
            $missions = Mission::where('id', '!=', $id)->get();
            if($missions){
                foreach($missions as $mission){
                    $mission->status = false;
                    $mission->update();
                }
            }
            Session::flash('success', strtoupper($missionID->name).' activated successfully!');
        }
        return back();
    }
}

app/Http/Controllers/Admin/Component/VisionController.php
<?php

namespace App\Http\Controllers\Admin\Component;

use App\Http\Controllers\Controller;
use Auth;
use Session;
use App\Vision;
use Illuminate\Http\Request;

class VisionController extends Controller
{
    public function __construct() {

        $this->middleware('auth:admin');
    }
    
    public function index() { 
        $visions = Vision::all();
        return view('admin.component.vision', compact('visions'));
    }
    
    public function storeVision(Request $request){

        $this->validate($request, [
            "vision"  => "required",
        ]);
  
        $vision = new Vision;
  
        $vision->name = $request->vision;
  
        if($vision->save() == true){
          Session::flash('success', 'Vision has been added successfully');
        }else{
          Session::flash('error', 'Could not add Vision');
        }
        return redirect(route('admin.component.vision.index'));
    }

    public function updateVision(Request $request){

        $visionId = $request->vision_id;

        $vision = Vision::find($visionId);

        $vision->name = $request->vision_name;

        if ($vision->update() == true) {
            Session::flash('success', 'Vision Updated Successfully');
        }else{
            Session::flash('failed', 'Error while Updating Vision');
        }
        return redirect(route('admin.component.vision.index'));
    }
    
    public function visionStatus($id) {

        $visionID = Vision::find($id);

        if ($visionID->status == true) {
            $visionID->status = false;
            $visionID->update();
                
            $visions = Vision::where('id', '!=', $id)->get();
            if($visions){
                foreach($visions as $vision){
                    $vision->status = true;
                    $vision->update();
                }
            }
            Session::flash('success', strtoupper($visionID->name).' disabled successfully!');
        }
        else{
            $visionID->status = true;
            $visionID->update();
                
            $visions = Vision::where('id', '!=', $id)->get();
            if($visions){
                foreach($visions as $vision){
                    $vision->status = false;
                    $vision->update();
                }
            }
            Session::flash('success', strtoupper($visionID->name).' activated successfully!');
        }
        return back();
    }
}

resources/views/admin/component/mandate.blade.php
@component('../partials.admin.header')
@endcomponent

<body >

<!-- /.wrapper -->
<div class="wrapper animsition has-footer">

    @component('../partials.admin.topnav')
    @endcomponent

    @component('../partials.admin.sidenav')
    @endcomponent 
    <!-- Start Main Container -->
    <div class="main-container">

        <div class="content-wrap">
            <!-- /. button panel -->
            <div class="panel panel-default">
                <div class="panel-body">
                    <button type="button" class="btn btn-info btn-hollow" data-toggle="modal" data-target="#addMandateModal"><i class="icon-floppy-disk m-r-5"></i>Add Mandate</button>
                </div>
            </div><!-- /.panel -->

            <div class="panel panel-default">
                <div class="panel-heading font-header">Mandate</div>
                    <div class="table-responsive">
                        <table class="table table-striped font-12" id="datatable">
                            <thead>
                                <tr>
                                    <th>S/N</th>
                                    <th >Mandate</th>
                                    <th >Date Created</th>
                                    <th >Status</th>
                                    <th >Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($mandates as $mandate)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td id="id_td" >{!!$mandate->name!!}</td>
                                    <td >{{$mandate->created_at}}</td>
                                    <td >
                                        @if( $mandate->status == 1)
                                            <a class="badge badge-success" href="{{ route('admin.component.mandate.status',$mandate->id) }}">
                                            <i class="fa fa-power-off"></i> Is active</a>
                                        @else
                                            <a class="badge badge-danger" href="{{ route('admin.component.mandate.status',$mandate->id) }}">
                                            <i class="fa fa-power-off"></i> Not active</a>
                                        @endif
                                    </td>
                                    <td >
                                        <a class="btn btn-warning btn-lg btn-icon btn-rounded btn-hollow edit_mandate" data-mandate-id="{{ $mandate['id']}}" data-mandate-name="{{ $mandate['name']}}"><i class="fa fa-edit"></i></a>
                                        <a class="btn btn-info btn-lg btn-icon btn-rounded btn-hollow view_mandate" data-mandate-view="{{ $mandate['name']}}"><i class="fa fa-edit"></i></a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- End Main Container -->

    <!-- Add Mandate Modal -->
    <div class="modal modal-scale fade" id="addMandateModal" tabindex="-1" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">Global Impact Mandate</h4>
            </div>
            <form  method="post" action="{{ route('admin.component.mandate.store') }}">
            {{csrf_field()}}
                <div class="modal-body">
                    <div class="form-group">
                        <label for="mandate">Mandate</label>
                        <textarea class="form-control" name="mandate" id="mandate" cols="50" rows="10" placeholder="Write Something..." required></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-gray" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-main">Submit</button>
                </div>
            </form>
          </div>
        </div>
    </div>
    <!-- End of Add Mandate Modal -->

    <!-- Edit Mandate Modal -->
    <div class="modal modal-scale" id="editMandateModal" tabindex="-1" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">Global Impact Mandate</h4>
            </div>
            <form  method="post" action="{{ route('admin.component.mandate.update') }}">
            {{csrf_field()}}
            <input name="mandate_id" id="mandate_id" value="" required type="hidden">
                <div class="modal-body">
                    <div class="form-group">
                        <label for="mandate_name">Mandate</label>
                        <textarea class="form-control" name="mandate_name" id="mandate_name" cols="50" rows="10" placeholder="Write Something..." required></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-gray" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-main">Update</button>
                </div>
            </form>
          </div>
        </div>
    </div>
    <!-- End of Edit Mandate Modal -->

    <!-- View Mandate Modal -->
    <div class="modal modal-scale" id="viewMandateModal" tabindex="-1" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">Global Impact Mandate</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="mandate_view">Mandate</label>
                    <textarea class="form-control" name="mandate_view" id="mandate_view" cols="50" rows="10" disabled></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-gray" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
    </div>
    <!-- End of View Mandate Modal -->


    @component('../partials.admin.footer')
    @endcomponent

    <script type="text/javascript">
        CKEDITOR.replace( 'mandate' );
        CKEDITOR.replace( 'mandate_name' );
        CKEDITOR.replace( 'mandate_view' );

        // $(function()  {
            $('#datatable').DataTable();
        // });

        // $(document).ready(function() {

            //  Script for Edit Mandate Modal
            $(document).on('click', '.edit_mandate', function(event) {
                // console.log('this');
                $('#editMandateModal').modal('show');

                var mandate_id = $(this).data("mandate-id");
                var mandate_name = $(this).data("mandate-name");

                $('input[name="mandate_id"]').val(mandate_id);
                // $('textarea[name="mandate_name"]').val(mandate_name);
                CKEDITOR.instances['mandate_name'].setData(mandate_name);
            });
            // End Script for Edit Mandate Modal

            //  Script for View Mandate Modal
            $(document).on('click', '.view_mandate', function(event) {
                // console.log('this');
                $('#viewMandateModal').modal('show');

                var mandate_view = $(this).data("mandate-view");

                // $('textarea[view="mandate_view"]').val(mandate_view);
                CKEDITOR.instances['mandate_view'].setData(mandate_view);
            });
            // End Script for View Mandate Modal
                
        // });
    </script>
    </body>
</html>

resources/views/admin/component/mission.blade.php
@component('../partials.admin.header')
@endcomponent

<body >

<!-- /.wrapper -->
<div class="wrapper animsition has-footer">

    @component('../partials.admin.topnav')
    @endcomponent

    @component('../partials.admin.sidenav')
    @endcomponent 
    <!-- Start Main Container -->
    <div class="main-container">

        <div class="content-wrap">
            <!-- /. button panel -->
            <div class="panel panel-default">
                <div class="panel-body">
                    <button type="button" class="btn btn-info btn-hollow" data-toggle="modal" data-target="#addMissionModal"><i class="icon-floppy-disk m-r-5"></i>Add Mission</button>
                </div>
            </div><!-- /.panel -->

            <div class="panel panel-default">
                <div class="panel-heading font-header">Mission</div>
                    <div class="table-responsive">
                        <table class="table table-striped font-12" id="datatable">
                            <thead>
                                <tr>
                                    <th>S/N</th>
                                    <th>Mission</th>
                                    <th>Date Created</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($missions as $mission)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td  id="id_td" >{!!$mission->name!!}</td>
                                    <td>{{$mission->created_at}}</td>
                                    <td>
                                        @if( $mission->status == 1)
                                            <a class="badge badge-success" href="{{ route('admin.component.mission.status',$mission->id) }}">
                                            <i class="fa fa-power-off"></i> Is active</a>
                                        @else
                                            <a class="badge badge-danger" href="{{ route('admin.component.mission.status',$mission->id) }}">
                                            <i class="fa fa-power-off"></i> Not active</a>
                                        @endif
                                    </td>
                                    <td>
                                        <a id="edit_mission" class="btn btn-warning btn-lg btn-icon btn-rounded btn-hollow" data-mission-id="{{ $mission['id']}}" data-mission-name="{{ $mission['name']}}"><i class="fa fa-edit"></i></a>
                                        <a id="view_mission" class="btn btn-info btn-lg btn-icon btn-rounded btn-hollow" data-mission-view="{{ $mission['name']}}"><i class="fa fa-edit"></i></a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- End Main Container -->

    <!-- Add Mission Modal -->
    <div class="modal modal-scale fade" id="addMissionModal" tabindex="-1" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">Global Impact Mission</h4>
            </div>
            <form  method="post" action="{{ route('admin.component.mission.store') }}">
            {{csrf_field()}}
                <div class="modal-body">
                    <div class="form-group">
                        <label for="mission">Mission</label>
                        <textarea class="form-control" name="mission" id="mission" cols="50" rows="10" placeholder="Write Something..." required></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-gray" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-main">Submit</button>
                </div>
            </form>
          </div>
        </div>
    </div>
    <!-- End of Add Mission Modal -->

    <!-- Edit Mission Modal -->
    <div class="modal modal-scale fade" id="editMissionModal" tabindex="-1" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">Global Impact Mission</h4>
            </div>
            <form  method="post" action="{{ route('admin.component.mission.update') }}">
            {{csrf_field()}}
            <input name="mission_id" id="mission_id" value="" required type="hidden">
                <div class="modal-body">
                    <div class="form-group">
                        <label for="mission_name">Mission</label>
                        <textarea class="form-control" value="" name="mission_name" id="mission_name" cols="50" rows="10" placeholder="Write Something..." required></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-gray" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-main">Update</button>
                </div>
            </form>
          </div>
        </div>
    </div>
    <!-- End of Edit Mission Modal -->

    <!-- View Mission Modal -->
    <div class="modal modal-scale" id="viewMissionModal" tabindex="-1" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">Global Impact Mission</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label for="mission_view">Mission</label>
                    <textarea class="form-control" name="mission_view" id="mission_view" cols="50" rows="10" disabled></textarea>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-gray" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
    </div>
    <!-- End of View Mandate Modal -->


    @component('../partials.admin.footer')
    @endcomponent
    
    <script>
        CKEDITOR.replace( 'mission' );
        CKEDITOR.replace( 'mission_name' );
        CKEDITOR.replace( 'mission_view' );

        // $(function()  {
            $('#datatable').DataTable();
        // });

        // $(document).ready(function() {

            //  Script for Edit Mission Modal
            $(document).on('click', '#edit_mission', function(event) {
                $('#editMissionModal').modal('show');

                var mission_id = $(this).data("mission-id");
                var mission_name = $(this).data("mission-name");

                $('input[name="mission_id"]').val(mission_id);
                // $('input[name="mission_name"]').val(mission_name);
                CKEDITOR.instances['mission_name'].setData(mission_name);
            });
            // End Script for Edit Mission Modal

            //  Script for View Mission Modal
            $(document).on('click', '#view_mission', function(event) {
                $('#viewMissionModal').modal('show');

                var mission_view = $(this).data("mission-view");

                CKEDITOR.instances['mission_view'].setData(mission_view);
            });
            // End Script for View Mission Modal
                
        // });
    </script>

    </body>
</html>