routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('/auth')->name('auth.')->group(function () {
    
    // Admin Routes
    Route::get('/admin_login',  'Auth\Admin\LoginController@loginPage')->name('admin_login');
    Route::post('/login_admin',  'Auth\Admin\LoginController@login')->name('login_admin');
    Route::get('/logout_admin',  'Auth\Admin\LoginController@logout')->name('logout_admin');
    // End of Admin Routes
});


Route::prefix('/admin')->name('admin.')->group(function () {
    #Dashboard Routes
    Route::get('/dashboard',  'Admin\DashboardController@dashboard')->name('dashboard');

    // Component Routes

    // Mandate Routes
    Route::get('/component/mandate/index',  'Admin\Component\MandateController@index')->name('component.mandate.index');
    Route::post('/component/mandate/store',  'Admin\Component\MandateController@storeMandate')->name('component.mandate.store');
    Route::post('/component/mandate/update',  'Admin\Component\MandateController@updateMandate')->name('component.mandate.update');
    Route::get('/component/mandate/status/{id}',  'Admin\Component\MandateController@mandateStatus')->name('component.mandate.status');
    // End of Mandate Routes

    // Mission Routes
    Route::get('/component/mission/index',  'Admin\Component\MissionController@index')->name('component.mission.index');
    Route::post('/component/mission/store',  'Admin\Component\MissionController@storeMission')->name('component.mission.store');
    Route::post('/component/mission/update',  'Admin\Component\MissionController@updateMission')->name('component.mission.update');
    Route::get('/component/mission/status/{id}',  'Admin\Component\MissionController@missionStatus')->name('component.mission.status');
    // End of Mission Routes

    // Vision Routes
    Route::get('/component/vision/index',  'Admin\Component\VisionController@index')->name('component.vision.index');
    Route::post('/component/vision/store',  'Admin\Component\VisionController@storeVision')->name('component.vision.store');
    Route::post('/component/vision/update',  'Admin\Component\VisionController@updateVision')->name('component.vision.update');
    Route::get('/component/vision/status/{id}',  'Admin\Component\VisionController@visionStatus')->name('component.vision.status');
    // End of Vision Routes

    // End of Component Routes

    // Blog Routes
    Route::get('/blog/index',  'Admin\BlogController@index')->name('blog.blog_index');
    Route::get('/blog/add',  'Admin\BlogController@addBlog')->name('blog.blog_add');
    Route::post('/blog/store',  'Admin\BlogController@storeBlog')->name('blog.blog_store');
    Route::get('/blog/edit/{id}',  'Admin\BlogController@editBlog')->name('blog.blog_edit');
    Route::post('/blog/update',  'Admin\BlogController@updateBlog')->name('blog.blog_update');
    Route::get('/blog/status/{id}',  'Admin\BlogController@blogStatus')->name('blog.blog_status');
    // End of Blog Routes

    // Admin Routes
    Route::get('/user/admin/index',  'Admin\User\AdminController@index')->name('user.admin.index');
    Route::get('/user/admin/add',  'Admin\User\AdminController@addAdmin')->name('user.admin.add');
    Route::post('/user/admin/store',  'Admin\User\AdminController@storeAdmin')->name('user.admin.store');
    Route::get('/user/admin/edit/{id}',  'Admin\User\AdminController@editAdmin')->name('user.admin.edit');
    Route::post('/user/admin/update',  'Admin\User\AdminController@updateAdmin')->name('user.admin.update');
    Route::get('/user/admin/status/{id}',  'Admin\User\AdminController@adminStatus')->name('user.admin.status');
    // End of Admin Routes

    // Admin Profile Routes
    Route::get('/user/admin/profile',  'Admin\User\AdminController@profile')->name('user.admin.profile');
    Route::post('/user/admin/profile_update',  'Admin\User\AdminController@updateProfile')->name('user.admin.profile_update');
    // End of Admin Profile Routes

     // Team Routes
     Route::get('/team/index',  'Admin\TeamController@index')->name('team.team_index');
     Route::post('/team/store',  'Admin\TeamController@storeTeam')->name('team.team_store');
     Route::get('/team/edit/{id}',  'Admin\TeamController@editTeam')->name('team.team_edit');
     Route::post('/team/update',  'Admin\TeamController@updateTeam')->name('team.team_update');
     Route::get('/team/status/{id}',  'Admin\TeamController@teamStatus')->name('team.team_status');
     Route::get('/team/delete/{id}',  'Admin\TeamController@deleteTeam')->name('team.team_delete');
     // End of Team Routes

     // Event Routes
     Route::get('/event/index',  'Admin\EventController@index')->name('event.event_index');
     Route::post('/event/store',  'Admin\EventController@storeEvent')->name('event.event_store');
     Route::get('/event/edit/{id}',  'Admin\EventController@editEvent')->name('event.event_edit');
     Route::post('/event/update',  'Admin\EventController@updateEvent')->name('event.event_update');
     Route::get('/event/status/{id}',  'Admin\EventController@eventStatus')->name('event.event_status');
    //  Route::get('/event/delete/{id}',  'Admin\EventController@deleteEvent')->name('event.event_delete');
     // End of Event Routes
});

    
    // Welcome Routes
    Route::get('/',  'Welcome\WelcomeController@index');
    // End of Welcome Routes

resources/views/partials/admin/footer.blade.php
<!-- Bootstrap -->
   
<script src="/assets/backend/js/bootstrap.min.js"></script> <!-- Modernizr -->

<script src="/assets/backend/js/modernizr.min.js"></script> <!-- Slim Scroll -->

<script src="/assets/backend/js/jquery.slimscroll.min.js"></script> <!-- Animsition -->

<script src="/assets/backend/js/jquery.animsition.min.js"></script> <!-- Sparkline -->

<script src="/assets/backend/js/jquery.sparkline.min.js"></script> <!-- Flot -->

<script src="/assets/backend/js/jquery.flot.min.js"></script> <!-- Simple Calendar -->

<script src="/assets/backend/js/uncompressed/simplecalendar.js"></script> <!-- Skycons -->

<script src='/assets/backend/js/uncompressed/skycons.js'></script> <!-- Noty -->

<script src="/assets/backend/js/jquery.noty.packaged.min.js"></script> <!-- Cookie -->

<script src='/assets/backend/js/uncompressed/jquery.cookie.js'></script> <!-- App -->

<script src="/assets/backend/js/app.min.js"></script> 

<script src="/assets/backend/js/ckeditor/ckeditor.js"></script>

<!-- Datatable -->
<script src="/assets/backend/js/jquery.dataTables.min.js"></script>
<script src="/assets/backend/js/dataTables.bootstrap.min.js"></script>


<script>

    $(function()  {
        //Theme Setting, change color of charts
        $('.color-list > li > span').click(function() {
        mainColor = $(this).data('color');
        initChart();
        });

        var mainColor = '#5090F7';
        var secondaryColor = '#34495e';

        ////initialize all charts
        initChart();

        function initChart()  {        
        var data = [{ data: [[0, 5], [1, 8], [2, 5], [3, 8], [4, 7], [5,9], [6, 8], [7, 8], [8, 10], [9, 12], [10, 10], [11, 5], [12, 9]],
            label: "Mobile Application"
        },
            { data: [[0, 8], [1, 9], [2, 12], [3, 11], [4, 13], [5,9], [6, 10], [7, 9], [8, 9], [9, 8], [10, 10], [11, 12], [12, 13]],
            label: "Web Application"
        }],

        options = { 
            xaxis: {
            ticks: [[1, 'Jan'], [2, 'Feb'], [3, 'Mar'], [4, 'Apr'], [5, 'May'], [6, 'Jun'], [7, 'Jul'], [8, 'Aug'], [9, 'Sep'], [10, 'Oct'], [11, 'Nov'], [12, 'Dec']]
            },
            series: {
            lines: {
                show: true, 
            },
            points: {
                show: true,
                radius: '3.5'
            },
            shadowSize: 0
            },
            grid: {
            hoverable: true,
            clickable: true,
            color: '#bbb',
            borderWidth: 1,
            borderColor: '#eee'
            },
            colors: [mainColor,secondaryColor]
        },
        plot;

        //Area Chart
        var areaData = [{ 
            data: [[0, 5], [1, 8], [2, 5], [3, 8], [4, 7], [5,9], [6, 8]],
            label: "Follower"
            }
        ],

        areaOptions = { 
            xaxis: {
            ticks: [[1, 'Mon'], [2, 'Tue'], [3, 'Wed'], [4, 'Thr'], [5, 'Fri'], [6, 'Sat'], [7, 'Sun']]
            },
            series: {
            lines: { 
                show: true, 
                fill: true
            },
            shadowSize: 0
            },
            grid: {
            hoverable: true,
            clickable: true,
            color: '#bbb',
            borderWidth: 1,
            borderColor: '#eee'
            },
            colors: [mainColor]
        },
        areaPlot;

        plot = $.plot($('.line-placeholder'), data, options);
        areaPlot = $.plot($('.area-placeholder'), areaData, areaOptions);

        $("<div id='tooltip'><\/div>").css({
            position: "absolute",
            display: "none",
            border: "1px solid #95a4b8",
            padding: "4px",
            "font-size": "12px",
            color: "#fff",
            "border-radius": "4px",
            "background-color": "#95a4b8",
            opacity: 0.90
        }).appendTo("body");

        $(".chart-placeholder").bind("plothover", function (event, pos, item) {
            var str = "(" + pos.x.toFixed(2) + ", " + pos.y.toFixed(2) + ")";
            $("#hoverdata").text(str);
        
            if (item) {
            var x = item.datapoint[0],
                y = item.datapoint[1];
            
                $("#tooltip").html(item.series.label+ " : " + y)
                .css({top: item.pageY+5, left: item.pageX+5})
                .fadeIn(200);
            } else {
            $("#tooltip").hide();
            }
        });

        //Sparkline
        $('.sparkbar').sparkline([15,19,20,22,33,27,31,27,19,30,21,10,15,18,25,9,11,14,16,10,15,16], {
            type: 'bar', 
            barColor: mainColor
        });
        $('.sparkline').sparkline([15,19,20,22,33,27,31,27,19,30,21,10,15,18,25,9,11,14,16,10,15,16,7,12,16,17,14,9,2,12,15,16,7,12,15,12,9,5,7,19,11,20,12,12], {
            type: 'line', 
            lineColor: mainColor,
            fillColor: false,
            maxSpotColor: false,
            minSpotColor: false,
            spotRadius: 0,
            highlightLineColor: secondaryColor
        });
        }

        //Redraw Charts
        $(window).resize(function() {
        initChart();
        });

        //Animated Weather Icons
        var iconLarge = new Skycons({"color": "white"});
        iconLarge.set("skycon1", "partly-cloudy-day");
        
        var iconsSmall = new Skycons({"color": "#7f888f"});
        iconsSmall.set("skycon2", "partly-cloudy-day");
        iconsSmall.set("skycon3", "sleet");
        iconsSmall.set("skycon4", "wind");
        iconsSmall.set("skycon5", "clear-day");
        
        iconLarge.play();
        iconsSmall.play();

        //Show event modal from clicking event on calendar
        $('tbody.event-calendar').on('click', '.event', function() {
        var monthEvent = $(this).attr('data-month');
        var dayEvent = $(this).text();
        var eventContent = $('.day-event[data-month="' + monthEvent + '"][data-day="' + dayEvent + '"]').children('.event-content').clone();

        var targetModal = $('#showEventModal');

        targetModal.find('.modal-body').append(eventContent);

        targetModal.modal('show');
        });

        $('#showEventModal').on('hidden.bs.modal', function (e) {  
        $(this).find('.modal-body').html('');
        });

        //Display notificaition
        $(window).load(function() {
        setTimeout(function() {
            noty({
                layout: 'topRight',
                text: '<strong>Mary Cormier<\/strong><br/>Hello, are you there?',
                theme: 'flat-noty noty-dark font-12',
                template: '<div class="noty_message has-image"><span class="noty_image"><img src="../img/profile5.jpg" class="profile-pic" alt=""><\/span><span class="noty_text"><\/span><div class="noty_close"><\/div><\/div>',
                type: '',
                timeout: '5000',
                animation: {
                open: 'animated flipInX',
                close: 'animated flipOutX',
                easing: 'swing', 
                speed: 500
                }
            });
        },2000);
        });        
    });
</script>

resources/views/partials/admin/header.blade.php
<!DOCTYPE html>
<html lang="en">
<!-- Mirrored from endlesstheme.com/quantum1.0.1/admin/sidemenu/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 02 May 2019 16:28:23 GMT -->
<head>
  <meta charset="utf-8">
  <title>Global Impact Admin</title>
  <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0"
        name="viewport">
  <meta content="telephone=no"
        name="format-detection">
  <meta content=""
        name="description">
  <meta content=""
        name="author"><!-- Bootstrap core CSS -->
  <link href="/assets/backend/css/bootstrap.min.css"
        rel="stylesheet"><!-- Icon Set -->
  <link href="/assets/backend/css/icon.css"
        rel="stylesheet"><!-- Font Awesome -->
  <link href="/assets/backend/css/font-awesome.min.css"
        rel="stylesheet"><!-- Animate Css -->
  <link href="/assets/backend/css/animate.min.css"
        rel="stylesheet"><!-- Animsition -->
  <link href="/assets/backend/css/animsition.min.css"
        rel="stylesheet"><!-- Core css -->
  <link class="core-css"
        href="/assets/backend/css/app.min.css"
        rel="stylesheet">

<!-- backend -->
<link href="/assets/backend/css/backend.css" rel="stylesheet">
<!-- Datatable -->
<link href="/assets/backend/css/dataTables.bootstrap.css" rel="stylesheet">


<!-- Jquery -->
<script src="/assets/backend/js/jquery-1.11.2.min.js"></script> 
</head>

resources/views/partials/admin/sidenav.blade.php
<!-- Start Side Navigation -->
<aside class="side-navigation-wrap sidebar-fixed">
    <div class="sidenav-inner">
        <ul class="side-nav magic-nav">
        
            <li class="first-link"><a href="{{ route('admin.dashboard') }}" class="animsition-link"><i class="icon-stats-dots"></i> <span class="nav-text">Dashboard</span></a></li>

            <li><a href="{{ route('admin.event.event_index') }}" class="animsition-link"><i class="icon-envelop"></i> <span class="nav-text">Upcoming Events</span></a></li>

            <li class="has-submenu">
              <a href="#submenu1" data-toggle="collapse" aria-expanded="false">
                <i class="icon-stack"></i> <span class="nav-text">Components</span>
                <span class="badge bg-danger">4</span>
              </a>
              <div class="sub-menu collapse secondary list-style-circle" id="submenu1">
                <ul>
                  <li><a href="{{ route('admin.component.mandate.index') }}" class="animsition-link">Mandate</a></li>
                  <li><a href="{{ route('admin.component.mission.index') }}" class="animsition-link">Mission</a></li>
                  <li><a href="{{ route('admin.component.vision.index') }}" class="animsition-link">Vision</a></li>
                </ul>
              </div>
            </li>
            <li class="has-submenu">
              <a href="#submenu4" data-toggle="collapse" aria-expanded="false">
                <i class="icon-file-text2"></i> <span class="nav-text">Blog</span>
                <span class="badge bg-success">2</span>
              </a>
              <div class="sub-menu collapse secondary list-style-circle" id="submenu4">
                <ul>
                  <li><a href="{{ route('admin.blog.blog_index') }}" class="animsition-link">List of Blogs</a></li>
                  <li><a href="{{ route('admin.blog.blog_add') }}" class="animsition-link">Add Blog</a></li>
                </ul>
              </div>
            </li>

            <li class="has-submenu">
              <a href="#submenu5" data-toggle="collapse" aria-expanded="false">
                <i class="icon-user"></i> <span class="nav-text">Users</span>
                <span class="badge bg-danger">1</span>
              </a>
              <div class="sub-menu collapse secondary list-style-circle" id="submenu5">
                <ul>
                  <li><a href="{{ route('admin.user.admin.index') }}" class="animsition-link">Admin</a></li>
                </ul>
              </div>
            </li>

            <li><a href="{{ route('admin.team.team_index') }}" class="animsition-link"><i class="icon-users"></i> <span class="nav-text">Team</span></a></li>

            <li><a href="" class="animsition-link" disabled><i class="icon-clipboard"></i> <span class="nav-text">Roles and Priviledges</span></a></li>
        </ul>
    </div><!-- /.sidebar-inner -->
</aside>
<!-- End Side Navigation -->

resources/views/partials/admin/topnav.blade.php
<!-- Start Header -->
  <header class="header-top navbar">
    <div class="navbar-header">

      <a class="navbar-brand" href="/">G<span>lobal Impact</span></a>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="headerNavbarCollapse">
      <ul class="nav navbar-nav">
        <li class="hidden-xs"><a href="#" class="font-lg sidenav-size-toggle"><i class="icon-indent-decrease inline-block"></i></a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="user-profile dropdown">
          <a href="#" class="clearfix dropdown-toggle" data-toggle="dropdown">
            <div class="user-name">{{auth()->user()->email }}<span class="caret m-l-5"></span></div>
          </a>
          <ul class="dropdown-menu dropdown-animated pop-effect" role="menu">
            <li><a href="#editProfileModal" data-toggle="modal" >My Profile</a></li>
            <li><a href="{{ route('auth.logout_admin') }}">Logout</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </header>
<!-- End Header -->


<!-- Edit profile Modal -->
<div class="modal modal-scale fade" id="editProfileModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">Update Profile</h4>
        </div>
        <form  method="post" action="{{ route('admin.user.admin.profile_update') }}">
        {{csrf_field()}}
            <div class="modal-body">

                <div class="form-group">
                    <div class="col-sm-6">
                        <label for="lastname">Lastname</label>
                        <input type="text" name="lastname" id="lastname" class="form-control " required disabled value="{{ auth()->user()->lastname }}">
                    </div>
                
                    <div class="col-sm-6">
                        <label for="firstname">Firstname</label>
                        <input type="text" class="form-control" name="firstname" id="firstname" required disabled value="{{ auth()->user()->firstname }}">
                    </div>
                </div>
                
                <div class="form-group">
                    <div class="col-sm-6">
                        <label for="othername">Othername</label>
                        <input type="text" class="form-control" name="othername" id="othername" disabled value="{{ auth()->user()->othername }}">
                    </div>
                
                    <div class="col-sm-6">
                        <label for="email">Email Address</label>
                        <input type="email" class="form-control" name="email" id="email" required disabled value="{{ auth()->user()->email }}">
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-6">
                        <label for="gender">Gender</label>
                        <br>
                        MALE
                        <input type="radio" id="gender" name="gender" value="M" required>
                        FEMALE
                        <input type="radio" id="gender" name="gender" value="F" required>
                    </div>
                
                    <div class="col-sm-6">
                        <label for="role">Role</label>
                        <input type="text" class="form-control" name="role" id="role" placeholder="Role">
                    </div>
                </div>
                
                <div class="form-group">
                    <div class="col-sm-6">
                        <label for="address">Address</label>
                        <textarea class="form-control" name="address" id="address" required placeholder="Write Address..."> {{ auth()->user()->address }}</textarea>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-6">
                        <label for="phone_no">Phone Number</label>
                        <input type="number" class="form-control" name="phone_no" id="phone_no" required value="{{ auth()->user()->phonenumber }}" placeholder="Phone Number">
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-gray" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-main">Update</button>
            </div>
        </form>
      </div>
    </div>
</div>
<!-- End of Edit Profile Modal -->


<script>

  $(document).ready(function(){
      // $(".adminLoginForm").submit(function(e){
      //   $(document).on('click', '.edit_mandate', function(event) {
          
              $.ajax({
              url:'{{url("admin/user/admin/profile")}}',
              type:'get',
              success:function(data){
                  console.log(data);
                // $('input[name="role"]').val(courseunit_id);
              },
              error: function () {
                console.log(data);
              }
          });

      // });
  });
</script>