routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('/auth')->name('auth.')->group(function () {
    
    // Admin Routes
    Route::get('/admin_login',  'Auth\Admin\LoginController@loginPage')->name('admin_login');
    Route::post('/login_admin',  'Auth\Admin\LoginController@login')->name('login_admin');
    Route::get('/logout_admin',  'Auth\Admin\LoginController@logout')->name('logout_admin');
    // End of Admin Routes
});


Route::prefix('/admin')->name('admin.')->group(function () {
    #Dashboard Routes
    Route::get('/dashboard',  'Admin\DashboardController@dashboard')->name('dashboard');

    // Component Routes

    // Mandate Routes
    Route::get('/component/mandate/index',  'Admin\Component\MandateController@index')->name('component.mandate.index');
    Route::post('/component/mandate/store',  'Admin\Component\MandateController@storeMandate')->name('component.mandate.store');
    Route::post('/component/mandate/update',  'Admin\Component\MandateController@updateMandate')->name('component.mandate.update');
    Route::get('/component/mandate/status/{id}',  'Admin\Component\MandateController@mandateStatus')->name('component.mandate.status');
    // End of Mandate Routes

    // Mission Routes
    Route::get('/component/mission/index',  'Admin\Component\MissionController@index')->name('component.mission.index');
    Route::post('/component/mission/store',  'Admin\Component\MissionController@storeMission')->name('component.mission.store');
    Route::post('/component/mission/update',  'Admin\Component\MissionController@updateMission')->name('component.mission.update');
    Route::get('/component/mission/status/{id}',  'Admin\Component\MissionController@missionStatus')->name('component.mission.status');
    // End of Mission Routes

    // Vision Routes
    Route::get('/component/vision/index',  'Admin\Component\VisionController@index')->name('component.vision.index');
    Route::post('/component/vision/store',  'Admin\Component\VisionController@storeVision')->name('component.vision.store');
    Route::post('/component/vision/update',  'Admin\Component\VisionController@updateVision')->name('component.vision.update');
    Route::get('/component/vision/status/{id}',  'Admin\Component\VisionController@visionStatus')->name('component.vision.status');
    // End of Vision Routes

    // End of Component Routes

    // Blog Routes
    Route::get('/blog/index',  'Admin\BlogController@index')->name('blog.blog_index');
    Route::get('/blog/add',  'Admin\BlogController@addBlog')->name('blog.blog_add');
    Route::post('/blog/store',  'Admin\BlogController@storeBlog')->name('blog.blog_store');
    Route::get('/blog/edit/{id}',  'Admin\BlogController@editBlog')->name('blog.blog_edit');
    Route::post('/blog/update',  'Admin\BlogController@updateBlog')->name('blog.blog_update');
    Route::get('/blog/status/{id}',  'Admin\BlogController@blogStatus')->name('blog.blog_status');
    // End of Blog Routes

    // Admin Routes
    Route::get('/user/admin/index',  'Admin\User\AdminController@index')->name('user.admin.index');
    Route::get('/user/admin/add',  'Admin\User\AdminController@addAdmin')->name('user.admin.add');
    Route::post('/user/admin/store',  'Admin\User\AdminController@storeAdmin')->name('user.admin.store');
    Route::get('/user/admin/edit/{id}',  'Admin\User\AdminController@editAdmin')->name('user.admin.edit');
    Route::post('/user/admin/update',  'Admin\User\AdminController@updateAdmin')->name('user.admin.update');
    Route::get('/user/admin/status/{id}',  'Admin\User\AdminController@adminStatus')->name('user.admin.status');
    // End of Admin Routes

    // Admin Profile Routes
    Route::get('/user/admin/profile',  'Admin\User\AdminController@profile')->name('user.admin.profile');
    Route::post('/user/admin/profile_update',  'Admin\User\AdminController@updateProfile')->name('user.admin.profile_update');
    // End of Admin Profile Routes

     // Team Routes
     Route::get('/team/index',  'Admin\TeamController@index')->name('team.team_index');
     Route::post('/team/store',  'Admin\TeamController@storeTeam')->name('team.team_store');
     Route::get('/team/edit/{id}',  'Admin\TeamController@editTeam')->name('team.team_edit');
     Route::post('/team/update',  'Admin\TeamController@updateTeam')->name('team.team_update');
     Route::get('/team/status/{id}',  'Admin\TeamController@teamStatus')->name('team.team_status');
     Route::get('/team/delete/{id}',  'Admin\TeamController@deleteTeam')->name('team.team_delete');
     // End of Team Routes

     // Event Routes
     Route::get('/event/index',  'Admin\EventController@index')->name('event.event_index');
     Route::post('/event/store',  'Admin\EventController@storeEvent')->name('event.event_store');
     Route::get('/event/edit/{id}',  'Admin\EventController@editEvent')->name('event.event_edit');
     Route::post('/event/update',  'Admin\EventController@updateEvent')->name('event.event_update');
     Route::get('/event/status/{id}',  'Admin\EventController@eventStatus')->name('event.event_status');
    //  Route::get('/event/delete/{id}',  'Admin\EventController@deleteEvent')->name('event.event_delete');
     // End of Event Routes
});

    
    // Welcome Routes
    Route::get('/',  'Welcome\WelcomeController@index');
    // End of Welcome Routes

app/Team.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Team extends Model
{
    //
}

app/Http/Controllers/Admin/TeamController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Auth;
use Session;
use App\Team;

class TeamController extends Controller
{
    public function __construct() {

        $this->middleware('auth:admin');
    }
    
    public function index() {
        $teams = Team::all();
        return view('admin.team.team_index', compact('teams'));
    }

    public function storeTeam(Request $request){

        $this->validate($request, [
            "firstname"  => "required",
            "lastname"  => "required",
            "team_post"  => "required",
            "team_image"  => "required",
            
        ]);

        $image = $request->file('team_image');

        if($image){
            $filename = time().'-'.$image->getClientOriginalName();
            $destinationPath = public_path().'/storage/images/team/document';
            $image->move($destinationPath, $filename);
        }
        else{
            $filename = "avatar.png";
        }
  
        $team = new Team;
  
        $team->firstname = $request->firstname;
        $team->lastname = $request->lastname;
        $team->othername = $request->othername;
        $team->team_position = $request->team_post;
        $team->team_image = $filename;
  
        if($team->save() == true){
          Session::flash('success', 'Team Member has been added successfully');
        }else{
          Session::flash('error', 'Could not add Team Member');
        }
        return back();
    }

    public function teamStatus($id) {

        $teamID = Team::find($id);

        if ($teamID->status == true) {
            $teamID->status = false;
            $teamID->update();
                
            Session::flash('success', strtoupper($teamID->lastname).' disabled successfully!');
        }
        else{
            $teamID->status = true;
            $teamID->update();
                
            Session::flash('success', strtoupper($teamID->lastname).' activated successfully!');
        }
        return back();
    }

    public function editTeam($id){

        $teams = Team::find($id);
        return view('admin.team.team_edit', compact('teams'));
    }

    public function updateTeam(Request $request){

        $teamId = $request->team_id;
        $image = $request->file('team_image');

        $team = Team::find($teamId);

        if($image){
            $filename = time().'-'.$image->getClientOriginalName();
            $destinationPath = public_path().'/storage/images/team/document';
            $image->move($destinationPath, $filename);

            $team->team_image = $filename;
        }

        $team->firstname = $request->firstname;
        $team->lastname = $request->lastname;
        $team->othername = $request->othername;
        $team->team_position = $request->team_post;

        if ($team->update() == true) {
            Session::flash('success', 'Team Member Updated Successfully');
        }else{
            Session::flash('failed', 'Error while Updating Team Member');
        }
        return redirect(route('admin.team.team_index'));
    }
    
    public function deleteTeam($id){
        
        if(Team::where('id', '=', $id)->delete()){
            Session::flash('success', 'Team Member Deleted Successfully');
        }else{
            Session::flash('error', 'Error while Deleting Team Member');
        }
        return back();
    } 
}

resources/views/admin/team/team_edit.blade.php
@component('../partials.admin.header')
@endcomponent
<body >
<!-- /.wrapper -->
<div class="wrapper animsition has-footer">

    @component('../partials.admin.topnav')
    @endcomponent

    @component('../partials.admin.sidenav')
    @endcomponent 
    <!-- Start Main Container -->
    <div class="main-container">

        <div class="content-wrap">

            <!-- /. button panel -->
            <div class="panel panel-default">
                <div class="panel-body">
                <a href="{{ route('admin.team.team_index') }}" ><button type="submit" class="btn btn-grey btn-hollow" ><i class="icon-floppy-disk m-r-5"></i>Go Back</button></a>
                </div>
            </div><!-- /.panel -->

            <div class="panel panel-default">
                <div class="panel-heading font-header">EDIT TEAM DETAILS</div>
                <div class="panel-body">
                    <form method="post" action="{{ route('admin.team.team_update') }}" enctype="multipart/form-data">
                        {{csrf_field()}}
                        <div class="form-horizontal font-12">

                            <input type="hidden" name="team_id" id="team_id" class="form-control" value="{{$teams->id}}" required>

                            <div class="form-group">
                                <label for="lastname" class="col-sm-2 control-label">Lastname</label>
                                <div class="col-sm-10">
                                    <input type="text" name="lastname" id="lastname" class="form-control" value="{{$teams->lastname}}" required>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="firstname"  class="col-sm-2 control-label">Firstname</label>
                                <div class="col-sm-10">
                                    <input type="text" name="firstname" id="firstname" class="form-control" value="{{$teams->firstname}}" required>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="othername"  class="col-sm-2 control-label">Othername</label>
                                <div class="col-sm-10">
                                    <input type="text" name="othername" id="othername" class="form-control" value="{{$teams->othername}}">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="team_post"  class="col-sm-2 control-label">Team Member Position</label>
                                <div class="col-sm-10">
                                    <input type="text" name="team_post" id="team_post" class="form-control" value="{{$teams->team_position}}" required>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-2 control-label" for="team_image">Member's Picture</label>
                                <div class="col-sm-5">
                                    <img src="/storage/images/team/document/{{$teams['team_image']}}"  width="400" height="300">
                                </div>
                            
                                <div class="col-sm-5">
                                    <input type="file" name="team_image" id="team_image" class="form-control" >
                                </div>
                            </div>
                                    
                            <button type="submit" class="btn btn-main pull-right">Update</button>
                        </div>
                    </form>
                </div><!-- /.panel-body -->
            </div><!-- /.panel -->

        </div>
    </div>
    <!-- End Main Container -->

    <!-- Start Footer -->
    <footer class="footer">
    &copy; 2015. <b>Quantum Admin</b> by <b>Endless Theme</b>
    </footer>
    <!-- End Footer -->


    @component('../partials.admin.footer')
    @endcomponent

    </body>
</html>

resources/views/admin/team/team_index.blade.php
@component('../partials.admin.header')
@endcomponent

<body >
<!-- /.wrapper -->
<div class="wrapper animsition has-footer">

    @component('../partials.admin.topnav')
    @endcomponent

    @component('../partials.admin.sidenav')
    @endcomponent 
    <!-- Start Main Container -->
    <div class="main-container">

        <div class="content-wrap">

            <!-- /. button panel -->
            <div class="panel panel-default">
                <div class="panel-body">
                    <button type="button" class="btn btn-info btn-hollow" data-toggle="modal" data-target="#addTeamModal"><i class="icon-floppy-disk m-r-5"></i>Add Team Members</button>
                </div>
            </div><!-- /.panel -->

            <div class="panel panel-default">
                <div class="panel-heading font-header">Team Members</div>
                    <div class="table-responsive">
                        <table class="table table-striped font-12" id="datatable">
                            <thead>
                                <tr>
                                    <th>S/N</th>
                                    <th class="text-center">Name</th>
                                    <th class="text-center">Postion</th>
                                    <th class="text-center">Picture Uploaded</th>
                                    <th class="text-center">Status</th>
                                    <th class="text-center">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($teams as $team)
                                <tr>
                                    <td class="text-center">{{$loop->iteration}}</td>
                                    <td class="text-center">{{$team->lastname}} {{$team->firstname}} {{$team->othername}}</td>
                                    <td class="text-center">{{$team->team_position}}</td>
                                    <td class="text-center"><a target="_blank" href="/storage/images/team/document/{{$team['team_image']}}">{{$team->team_image}}</a></td>
                                    <td class="text-center">
                                        @if( $team->status == 1)
                                            <a class="badge badge-success" href="{{ route('admin.team.team_status',$team->id) }}">
                                            <i class="fa fa-power-off"></i> Is active</a>
                                        @else
                                            <a class="badge badge-danger" href="{{ route('admin.team.team_status',$team->id) }}">
                                            <i class="fa fa-power-off"></i> Not active</a>
                                        @endif
                                    </td>
                                    <td class="text-center">
                                        <a href="{{ route('admin.team.team_edit',$team->id) }}" class="btn btn-info btn-lg btn-icon btn-rounded btn-hollow " ><i class="fa fa-edit"></i></a>
                                        <a href="{{ route('admin.team.team_delete', $team->id) }}" onclick="return confirm('Are you sure you want to delete this Team Member?');" class="btn btn-danger btn-lg btn-icon btn-rounded btn-hollow "><i class="fa fa-trash"></i></a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Main Container -->

    <!-- Add Team Modal -->
    <div class="modal modal-scale fade" id="addTeamModal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">Global Impact Team</h4>
            </div>

            <form method="post" action="{{ route('admin.team.team_store') }}" enctype="multipart/form-data">
                {{csrf_field()}}
            
                <div class="modal-body">

                    <div class="form-horizontal font-12">
                        <div class="form-group">
                            <!-- <label for="lastname" class="col-sm-1">Lastname</label> -->
                            <div class="col-sm-6">
                                <input type="text" name="lastname" id="lastname" class="form-control" placeholder="Lastname" required>
                            </div>

                            <!-- <label for="firstname" class="col-sm-1">Firstname</label> -->
                            <div class="col-sm-6">
                                <input type="text" name="firstname" id="firstname" class="form-control" placeholder="Firstname" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <!-- <label for="othername" class="col-sm-1">Othername</label> -->
                            <div class="col-sm-6">
                                <input type="text" name="othername" id="othername" class="form-control" placeholder="Othername">
                            </div>

                            <!-- <label for="team_post" class="col-sm-1">Team Member Position</label> -->
                            <div class="col-sm-6">
                                <input type="text" name="team_post" id="team_post" class="form-control" placeholder="Team Position" required>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="team_image" class="col-sm-2 control-label">Member's Picture</label>
                            <div class="col-sm-8">
                                <input type="file" name="team_image" id="team_image" class="form-control" required>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-gray" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-main">Submit</button>
                </div>
                
            </form>
          </div>
        </div>
    </div>
    <!-- End of Add Team Modal -->

    <!-- Start Footer -->
    <footer class="footer">
    &copy; 2015. <b>Quantum Admin</b> by <b>Endless Theme</b>
    </footer>
    <!-- End Footer -->


    @component('../partials.admin.footer')
    @endcomponent

    </body>
</html>