routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('/auth')->name('auth.')->group(function () {
    
    // Admin Routes
    Route::get('/admin_login',  'Auth\Admin\LoginController@loginPage')->name('admin_login');
    Route::post('/login_admin',  'Auth\Admin\LoginController@login')->name('login_admin');
    Route::get('/logout_admin',  'Auth\Admin\LoginController@logout')->name('logout_admin');
    // End of Admin Routes
});


Route::prefix('/admin')->name('admin.')->group(function () {
    #Dashboard Routes
    Route::get('/dashboard',  'Admin\DashboardController@dashboard')->name('dashboard');

    // Component Routes

    // Mandate Routes
    Route::get('/component/mandate/index',  'Admin\Component\MandateController@index')->name('component.mandate.index');
    Route::post('/component/mandate/store',  'Admin\Component\MandateController@storeMandate')->name('component.mandate.store');
    Route::post('/component/mandate/update',  'Admin\Component\MandateController@updateMandate')->name('component.mandate.update');
    Route::get('/component/mandate/status/{id}',  'Admin\Component\MandateController@mandateStatus')->name('component.mandate.status');
    // End of Mandate Routes

    // Mission Routes
    Route::get('/component/mission/index',  'Admin\Component\MissionController@index')->name('component.mission.index');
    Route::post('/component/mission/store',  'Admin\Component\MissionController@storeMission')->name('component.mission.store');
    Route::post('/component/mission/update',  'Admin\Component\MissionController@updateMission')->name('component.mission.update');
    Route::get('/component/mission/status/{id}',  'Admin\Component\MissionController@missionStatus')->name('component.mission.status');
    // End of Mission Routes

    // Vision Routes
    Route::get('/component/vision/index',  'Admin\Component\VisionController@index')->name('component.vision.index');
    Route::post('/component/vision/store',  'Admin\Component\VisionController@storeVision')->name('component.vision.store');
    Route::post('/component/vision/update',  'Admin\Component\VisionController@updateVision')->name('component.vision.update');
    Route::get('/component/vision/status/{id}',  'Admin\Component\VisionController@visionStatus')->name('component.vision.status');
    // End of Vision Routes

    // End of Component Routes

    // Blog Routes
    Route::get('/blog/index',  'Admin\BlogController@index')->name('blog.blog_index');
    Route::get('/blog/add',  'Admin\BlogController@addBlog')->name('blog.blog_add');
    Route::post('/blog/store',  'Admin\BlogController@storeBlog')->name('blog.blog_store');
    Route::get('/blog/edit/{id}',  'Admin\BlogController@editBlog')->name('blog.blog_edit');
    Route::post('/blog/update',  'Admin\BlogController@updateBlog')->name('blog.blog_update');
    Route::get('/blog/status/{id}',  'Admin\BlogController@blogStatus')->name('blog.blog_status');
    // End of Blog Routes

    // Admin Routes
    Route::get('/user/admin/index',  'Admin\User\AdminController@index')->name('user.admin.index');
    Route::get('/user/admin/add',  'Admin\User\AdminController@addAdmin')->name('user.admin.add');
    Route::post('/user/admin/store',  'Admin\User\AdminController@storeAdmin')->name('user.admin.store');
    Route::get('/user/admin/edit/{id}',  'Admin\User\AdminController@editAdmin')->name('user.admin.edit');
    Route::post('/user/admin/update',  'Admin\User\AdminController@updateAdmin')->name('user.admin.update');
    Route::get('/user/admin/status/{id}',  'Admin\User\AdminController@adminStatus')->name('user.admin.status');
    // End of Admin Routes

    // Admin Profile Routes
    Route::get('/user/admin/profile',  'Admin\User\AdminController@profile')->name('user.admin.profile');
    Route::post('/user/admin/profile_update',  'Admin\User\AdminController@updateProfile')->name('user.admin.profile_update');
    // End of Admin Profile Routes

     // Team Routes
     Route::get('/team/index',  'Admin\TeamController@index')->name('team.team_index');
     Route::post('/team/store',  'Admin\TeamController@storeTeam')->name('team.team_store');
     Route::get('/team/edit/{id}',  'Admin\TeamController@editTeam')->name('team.team_edit');
     Route::post('/team/update',  'Admin\TeamController@updateTeam')->name('team.team_update');
     Route::get('/team/status/{id}',  'Admin\TeamController@teamStatus')->name('team.team_status');
     Route::get('/team/delete/{id}',  'Admin\TeamController@deleteTeam')->name('team.team_delete');
     // End of Team Routes

     // Event Routes
     Route::get('/event/index',  'Admin\EventController@index')->name('event.event_index');
     Route::post('/event/store',  'Admin\EventController@storeEvent')->name('event.event_store');
     Route::get('/event/edit/{id}',  'Admin\EventController@editEvent')->name('event.event_edit');
     Route::post('/event/update',  'Admin\EventController@updateEvent')->name('event.event_update');
     Route::get('/event/status/{id}',  'Admin\EventController@eventStatus')->name('event.event_status');
    //  Route::get('/event/delete/{id}',  'Admin\EventController@deleteEvent')->name('event.event_delete');
     // End of Event Routes
});

    
    // Welcome Routes
    Route::get('/',  'Welcome\WelcomeController@index');
    // End of Welcome Routes

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/User/AdminController.php
<?php

namespace App\Http\Controllers\Admin\User;

use App\Http\Controllers\Controller;
use Auth;
use Session;
use App\Admin;
use App\Role;
use Illuminate\Http\Request;

class AdminController extends Controller
{
    public function __construct() {

        $this->middleware('auth:admin');
    }
    
    public function index() { 
        $admins = Admin::with(['role',])->get();
        $roles = Role::all();
        return view('admin.user.index', compact('admins', 'roles'));
    }
    
    public function storeAdmin(Request $request){

        $this->validate($request, [
            "firstname"  => "required",
            "lastname"  => "required",
            "email"  => "required",
            "role"  => "required",
            "gender"  => "required",
        ]);
  
        $hash_password = bcrypt('password');

        $admin = new Admin;
  
        $admin->firstname = $request->firstname;
        $admin->lastname = $request->lastname;
        $admin->othername = $request->othername;
        $admin->email = $request->email;
        $admin->role_id = $request->role;
        $admin->gender = $request->gender;
        $admin->password = $hash_password;
  
        if($admin->save() == true){
          Session::flash('success', 'Admin has been added successfully');
        }else{
          Session::flash('error', 'Could not add Admin');
        }
        return redirect(route('admin.user.admin.index'));
    }

    public function editAdmin($id){

        $admin = Admin::find($id);
        $roles = Role::all();
        return view('admin.user.admin_edit', compact('admin', 'roles'));
    }

    public function updateAdmin(Request $request){

        $adminId = $request->admin_id;

        $admin = Admin::find($adminId);

        $admin->firstname = $request->firstname;
        $admin->lastname = $request->lastname;
        $admin->othername = $request->othername;
        $admin->email = $request->email;
        $admin->role_id = $request->role;
        $admin->gender = $request->gender;

        if ($admin->update() == true) {
            Session::flash('success', 'Admin Updated Successfully');
        }else{
            Session::flash('failed', 'Error while Updating Admin');
        }
        return redirect(route('admin.user.admin.index'));
    }

    public function adminStatus($id) {

        $adminID = Admin::find($id);

        if ($adminID->status == true) {
            $adminID->status = false;
            $adminID->update();
                
            Session::flash('success', strtoupper($adminID->lastname).' disabled successfully!');
        }
        else{
            $adminID->status = true;
            $adminID->update();
                
            Session::flash('success', strtoupper($adminID->lastname).' activated successfully!');
        }
        return back();
    }

    public function profile(){
        $applicant_log = Auth::guard('admin')->user();

        $admin = Admin::with(['role',])->find($applicant_log->id);
        return response()->json(['data'=>$admin]);
    }

    public function updateProfile(Request $request){

        $applicant_log = Auth::guard('admin')->user();

        $admin = Admin::find($applicant_log->id);

        $admin->address = $request->address;
        $admin->phonenumber = $request->phone_no;
        $admin->gender = $request->gender;

        if ($admin->update() == true) {
            Session::flash('success', strtoupper($admin->email).' Profile Updated Successfully');
        }else{
            Session::flash('failed', 'Error while Updating '.strtoupper($admin->email).' Profile');
        }
        return redirect(route('admin.user.admin.index'));
    }

}

resources/views/admin/user/admin_edit.blade.php
@component('../partials.admin.header')
@endcomponent

<body >
<!-- /.wrapper -->
<div class="wrapper animsition has-footer">

    @component('../partials.admin.topnav')
    @endcomponent

    @component('../partials.admin.sidenav')
    @endcomponent 
    <!-- Start Main Container -->
    <div class="main-container">

        <div class="content-wrap">
            
            <!-- /. button panel -->
            <div class="panel panel-default">
                <div class="panel-body">
                <a href="{{ route('admin.user.admin.index') }}" ><button type="submit" class="btn btn-grey btn-hollow" ><i class="icon-floppy-disk m-r-5"></i>Go Back</button></a>
                </div>
            </div><!-- /.panel -->

            <div class="panel panel-default">
                <div class="panel-heading font-header">EDIT ADMIN</div>
                <div class="panel-body">
                    <form method="post" action="{{ route('admin.user.admin.update') }}" >
                    {{csrf_field()}}
                            <input type="hidden" name="admin_id" id="admin_id" class="form-control" value="{{$admin->id}}" required>
                            <div class="form-group">
                                <div class="col-sm-6">
                                    <label for="lastname">Lastname</label>
                                    <input type="text" name="lastname" id="lastname" class="form-control " required value="{{$admin->lastname}}">
                                </div>
                            
                                <div class="col-sm-6">
                                    <label for="firstname">Firstname</label>
                                    <input type="text" class="form-control" name="firstname" id="firstname" class="form-control " required value="{{$admin->firstname}}">
                                </div>
                            </div>
                            
                            <div class="form-group">
                                <div class="col-sm-6">
                                    <label for="othername">Othername</label>
                                    <input type="text" class="form-control" name="othername" id="othername" class="form-control " value="{{$admin->othername}}">
                                </div>
                            
                                <div class="col-sm-6">
                                    <label for="email">Email Address</label>
                                    <input type="email" class="form-control" name="email" id="email" class="form-control " required value="{{$admin->email}}">
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-6">
                                    <label for="gender">Gender</label>
                                    <br>
                                    MALE
                                    <input type="radio" id="gender" name="gender" value="M" >
                                    FEMALE
                                    <input type="radio" id="gender" name="gender" value="F" >
                                </div>
                            
                                <div class="col-sm-6">
                                    <label for="role">Role</label>
                                    <select name="role" class="form-control" id="role" required>
                                        @foreach($roles as $role)
                                            <option value="{{$role['id']}}" <?php if($role['id'] == $admin['role_id']){ ?> selected <?php  } ?> > {{$role['name']}} </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            </br>
                            <button type="submit" class="btn btn-main ">Update</button>
                        </div><!-- /.form-horizontal -->
                    </form>
                </div><!-- /.panel-body -->
            </div><!-- /.panel -->

        </div>
    </div>
    <!-- End Main Container -->

    <!-- Start Footer -->
    <footer class="footer">
    &copy; 2015. <b>Quantum Admin</b> by <b>Endless Theme</b>
    </footer>
    <!-- End Footer -->


    @component('../partials.admin.footer')
    @endcomponent
    
    </body>
</html>

resources/views/admin/user/index.blade.php
@component('../partials.admin.header')
@endcomponent

<body >
<!-- /.wrapper -->
<div class="wrapper animsition has-footer">

    @component('../partials.admin.topnav')
    @endcomponent

    @component('../partials.admin.sidenav')
    @endcomponent 
    <!-- Start Main Container -->
    <div class="main-container">

        <div class="content-wrap">
            <!-- /. button panel -->
            <div class="panel panel-default">
                <div class="panel-body">
                    <button type="button" class="btn btn-info btn-hollow" data-toggle="modal" data-target="#editProfileModal"><i class="icon-floppy-disk m-r-5"></i>Add Admin</button>
                </div>
            </div><!-- /.panel -->

            <div class="panel panel-default">
                <div class="panel-heading font-header">Admin</div>
                    <div class="table-responsive">
                        <table class="table table-striped font-12" id="datatable">
                            <thead>
                                <tr>
                                    <th>S/N</th>
                                    <th class="text-center">Name</th>
                                    <th class="text-center">Email</th>
                                    <th class="text-center">Gender</th>
                                    <th class="text-center">Role</th>
                                    <th class="text-center">Status</th>
                                    <th class="text-center">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($admins as $admin)
                                <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td class="text-center">{{$admin->lastname}} {{$admin->firstname}} {{$admin->othername}}</td>
                                    <td class="text-center">{{$admin->email}}</td>
                                    <td class="text-center">{{$admin->gender}}</td>
                                    <td class="text-center">{{$admin->role->name}}</td>
                                    <td class="text-center">
                                        @if( $admin->status == 1)
                                            <a class="badge badge-success" href="{{ route('admin.user.admin.status',$admin->id) }}">
                                            <i class="fa fa-power-off"></i> Is active</a>
                                        @else
                                            <a class="badge badge-danger" href="{{ route('admin.user.admin.status',$admin->id) }}">
                                            <i class="fa fa-power-off"></i> Not active</a>
                                        @endif
                                    </td>
                                    <td class="text-center">
                                        <a href="{{ route('admin.user.admin.edit', $admin->id) }}" class="btn btn-info btn-lg btn-icon btn-rounded btn-hollow" ><i class="fa fa-edit"></i></a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- End Main Container -->

    <!-- Add Admin Modal -->
    <div class="modal modal-scale fade" id="addAdminModal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title">Add Admin</h4>
            </div>
            <form  method="post" action="{{ route('admin.user.admin.store') }}">
            {{csrf_field()}}
                <div class="modal-body">

                    <div class="form-group">
                        <div class="col-sm-6">
                            <label for="lastname">Lastname</label>
                            <input type="text" name="lastname" id="lastname" class="form-control " required placeholder="Lastname">
                        </div>
                    
                        <div class="col-sm-6">
                            <label for="firstname">Firstname</label>
                            <input type="text" class="form-control" name="firstname" id="firstname" class="form-control " required placeholder="Firstname">
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <div class="col-sm-6">
                            <label for="othername">Othername</label>
                            <input type="text" class="form-control" name="othername" id="othername" class="form-control " placeholder="Othername">
                        </div>
                    
                        <div class="col-sm-6">
                            <label for="email">Email Address</label>
                            <input type="email" class="form-control" name="email" id="email" class="form-control " required placeholder="Email Address">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-6">
                            <label for="gender">Gender</label>
                            <br>
                            MALE
                            <input type="radio" id="gender" name="gender" value="M" >
                            FEMALE
                            <input type="radio" id="gender" name="gender" value="F" >
                        </div>
                    
                        <div class="col-sm-6">
                            <label for="role">Role</label>
                            <select name="role" class="form-control" id="role" required>
                                <option selected>Select Role</option>
                                @foreach($roles as $role)
                                    <option value="{{$role['id']}}" > {{$role->name}} </option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-gray" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-main">Submit</button>
                </div>
            </form>
          </div>
        </div>
    </div>
    <!-- End of Add Admin Modal -->
    

    <!-- Start Footer -->
    <footer class="footer">
    &copy; 2015. <b>Quantum Admin</b> by <b>Endless Theme</b>
    </footer>
    <!-- End Footer -->


    @component('../partials.admin.footer')
    @endcomponent
    
    <script>

        $(function()  {
            $('#datatable').DataTable();
        });

    </script>

    </body>
</html>